name: Update Bib Using JabRef

on:
  issues:
    types: [opened]

jobs:
  update-bib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install JabRef CLI
        run: |
          curl -L -o jabref.tar.gz https://github.com/JabRef/jabref/releases/download/v5.15/JabRef-5.15-portable_linux.tar.gz
          mkdir jabref
          tar -xzf jabref.tar.gz -C jabref --strip-components=1
          chmod +x jabref/bin/JabRef
          echo "$GITHUB_WORKSPACE/jabref/bin" >> $GITHUB_PATH

      - name: Extract DOIs and update bib using JabRef
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt
          grep -v '^\s*$' issue_body.txt | while read -r doi; do
            echo "Importing: $doi"
            $GITHUB_WORKSPACE/jabref/bin --importToOpen "$doi" --output nablachem.bib
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add nablachem.bib
          git commit -m "Update nablachem.bib from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "DOIs processed and added to nablachem.bib."
