name: Update Bib from DOI Issue

on:
  issues:
    types: [opened]

jobs:
  update-bib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract DOIs and append BibTeX
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt
          
          # Extract non-empty lines (assume each line is a DOI)
          grep -v '^\s*$' issue_body.txt | while read -r doi; do
            # Escape special characters for curl
            encoded_doi=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$doi'''))")
            
            echo "Fetching: $doi"
            bibtex=$(curl -sLH "Accept: application/x-bibtex" "https://doi.org/$encoded_doi" || echo "")

            if [[ "$bibtex" == @* ]]; then
              echo "$bibtex" >> nablachem.bib
              echo "Appended BibTeX for: $doi"
            else
              echo "Warning: Failed to fetch BibTeX for: $doi"
            fi
          done

      - name: Commit and push bib update
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add nablachem.bib
          git commit -m "Update nablachem.bib from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push
